export { default as Skills } from './Skills'
export { default as Careers } from './Careers'
export { default as Intro } from './Intro'
export { default as Projects } from './Projects'
export { default as Footer } from './Footer'
