export { default as altong } from './altong.png?preset=thumbnail'
export { default as beliefy } from './beliefy.png?preset=thumbnail'
export { default as playwingsRenewal } from './playwings-renewal.png?preset=thumbnail'
export { default as playwingsWeb } from './playwings-web.png?preset=thumbnail'
export { default as proofy } from './proofy.png?preset=thumbnail'
export { default as pedsfolio } from '../background.png?preset=thumbnail'
